#!/usr/bin/env python3
from pathlib import Path
import subprocess


def read(path): return Path(path).read_text(encoding='utf-8')
def write(path,text): Path(path).write_text(text,encoding='utf-8')
def one(text,old,new,label):
    count=text.count(old)
    if count!=1: raise SystemExit(f'{label}: expected 1 match, found {count}')
    return text.replace(old,new,1)

policy=read('kerbside-train-movement-worker/movement-storage-policy.js')
policy=one(policy,"export const LIVE_RETENTION_MS=12*60*60*1000;\nexport const RECOVERY_RETENTION_MS=48*60*60*1000;\nexport const RECOVERY_CHUNK_SIZE=300;","export const LIVE_RETENTION_MS=4*60*60*1000;\nexport const RECOVERY_RETENTION_MS=36*60*60*1000;\nexport const RECOVERY_CHUNK_SIZE=100;\nexport const MAX_LIVE_SNAPSHOTS=10000;\nexport const MAX_RECOVERED_SNAPSHOTS=12000;\nexport const INDEX_REBUILD_MS=5*60*1000;\nexport const RECOVERY_LOAD_PAGE_SIZE=60;\nexport const RECOVERY_LOAD_MAX_PAGES=12;",'policy bounds')
policy=one(policy,"export function compactRecoverySnapshot(s){if(!s||typeof s!=='object')return null;const out={trainId:text(s.trainId),uid:text(s.uid),headcode:text(s.headcode),date:text(s.date),status:text(s.status)||'unknown',updatedAt:Number(s.updatedAt)||Date.now()};for(const k of ['activation','lastEvent','cancellation','reinstatement','originChange','identityChange','locationChange','currentTrainId'])if(s[k]!=null)out[k]=s[k];return out.trainId?out:null;}","export function compactRecoverySnapshot(s){if(!s||typeof s!=='object')return null;const out={trainId:text(s.trainId),uid:text(s.uid),headcode:text(s.headcode),date:text(s.date),status:text(s.status)||'unknown',updatedAt:Number(s.updatedAt)||Date.now()};for(const k of ['activation','lastEvent','cancellation','reinstatement','originChange','identityChange','locationChange','currentTrainId'])if(s[k]!=null)out[k]=s[k];return out.trainId?out:null;}\nexport function compactLiveSnapshot(s,{historyLimit=0}={}){const out=compactRecoverySnapshot(s);if(!out)return null;const limit=Math.max(0,Math.min(4,Math.floor(Number(historyLimit)||0))),history=Array.isArray(s.history)?s.history.slice(-limit):[];if(history.length)out.history=history;return out;}",'live compaction')
write('kerbside-train-movement-worker/movement-storage-policy.js',policy)

test=read('kerbside-train-movement-worker/movement-storage-policy.test.mjs')
test=one(test,"import{HOT_CHECKPOINT_MS,RECOVERY_PREFIX,compactRecoverySnapshot,recoveryKey,recoveryKeyExpired,shouldQueueRecovery,splitRecoveryEntries}from'./movement-storage-policy.js';","import{HOT_CHECKPOINT_MS,MAX_LIVE_SNAPSHOTS,MAX_RECOVERED_SNAPSHOTS,RECOVERY_CHUNK_SIZE,RECOVERY_PREFIX,compactLiveSnapshot,compactRecoverySnapshot,recoveryKey,recoveryKeyExpired,shouldQueueRecovery,splitRecoveryEntries}from'./movement-storage-policy.js';",'test imports')
test=one(test,"test('compact recovery omits rolling history',()=>{const row=compactRecoverySnapshot({trainId:'123A45',status:'running',updatedAt:99,history:[{x:1}],lastEvent:{eventType:'DEPARTURE'}});assert.equal(row.lastEvent.eventType,'DEPARTURE');assert.equal(Object.hasOwn(row,'history'),false);});","test('compact recovery omits rolling history',()=>{const row=compactRecoverySnapshot({trainId:'123A45',status:'running',updatedAt:99,history:[{x:1}],lastEvent:{eventType:'DEPARTURE'}});assert.equal(row.lastEvent.eventType,'DEPARTURE');assert.equal(Object.hasOwn(row,'history'),false);});\ntest('live cache strips cold history and caps hot history',()=>{const history=Array.from({length:12},(_,i)=>({eventType:'DEPARTURE',i})),base={trainId:'123A45',status:'running',updatedAt:99,history,lastEvent:history.at(-1)};assert.equal(Object.hasOwn(compactLiveSnapshot(base),'history'),false);assert.deepEqual(compactLiveSnapshot(base,{historyLimit:4}).history.map(x=>x.i),[8,9,10,11]);assert.ok(MAX_LIVE_SNAPSHOTS<=10000);assert.ok(MAX_RECOVERED_SNAPSHOTS<=12000);});",'live cache test')
test=one(test,"test('buckets are bounded and expire',()=>{assert.deepEqual(splitRecoveryEntries(Array.from({length:601},(_,i)=>({trainId:String(i)})),300).map(x=>x.length),[300,300,1]);const key=recoveryKey(1_000_000,2);assert.ok(key.startsWith(RECOVERY_PREFIX));assert.equal(recoveryKeyExpired(key,1_000_100,200),false);assert.equal(recoveryKeyExpired(key,1_000_201,200),true);});","test('buckets are bounded and expire',()=>{assert.equal(RECOVERY_CHUNK_SIZE,100);assert.deepEqual(splitRecoveryEntries(Array.from({length:201},(_,i)=>({trainId:String(i)}))).map(x=>x.length),[100,100,1]);const key=recoveryKey(1_000_000,2);assert.ok(key.startsWith(RECOVERY_PREFIX));assert.equal(recoveryKeyExpired(key,1_000_100,200),false);assert.equal(recoveryKeyExpired(key,1_000_201,200),true);});",'bucket test')
test=one(test,"test('worker has no hot-path SQL mutation',()=>{const source=fs.readFileSync(new URL('./worker.js',import.meta.url),'utf8');assert.doesNotMatch(source,/INSERT OR REPLACE|DELETE FROM/i);assert.match(source,/storage\\.put\\(recoveryKey\\(/);});","test('worker has no hot-path SQL mutation',()=>{const source=fs.readFileSync(new URL('./worker.js',import.meta.url),'utf8');assert.doesNotMatch(source,/INSERT OR REPLACE|DELETE FROM/i);assert.match(source,/storage\\.put\\(recoveryKey\\(/);assert.match(source,/compactLiveSnapshot\\(snapshot/);assert.match(source,/limit:RECOVERY_LOAD_PAGE_SIZE/);});",'worker guard')
write('kerbside-train-movement-worker/movement-storage-policy.test.mjs',test)

worker=read('kerbside-train-movement-worker/worker.js')
worker=one(worker,"  HOT_TRAIN_TTL_MS, LIVE_RETENTION_MS, RECOVERY_CHUNK_SIZE, RECOVERY_FLUSH_MS, RECOVERY_PREFIX, RECOVERY_RETENTION_MS,\n  compactRecoverySnapshot, recoveryKey, recoveryKeyExpired, shouldQueueRecovery, splitRecoveryEntries","  HOT_TRAIN_TTL_MS, INDEX_REBUILD_MS, LIVE_RETENTION_MS, MAX_LIVE_SNAPSHOTS, MAX_RECOVERED_SNAPSHOTS, RECOVERY_CHUNK_SIZE, RECOVERY_FLUSH_MS, RECOVERY_LOAD_MAX_PAGES, RECOVERY_LOAD_PAGE_SIZE, RECOVERY_PREFIX, RECOVERY_RETENTION_MS,\n  compactLiveSnapshot, compactRecoverySnapshot, recoveryKey, recoveryKeyExpired, shouldQueueRecovery, splitRecoveryEntries",'worker imports')
worker=one(worker,"    this.lastRecoveryFlushAt=0; this.lastMemoryPruneAt=0; this.lastStorageCleanupAt=0; this.recoveryFlushPromise=null;","    this.lastRecoveryFlushAt=0; this.lastMemoryPruneAt=0; this.lastIndexRebuildAt=0; this.lastStorageCleanupAt=0; this.recoveryFlushPromise=null;",'index timer')
old="""  rememberRecovered(snapshot,source='recovery'){if(!snapshot||!snapshot.trainId)return;const prior=this.recoveredSnapshots.get(snapshot.trainId);if(!prior||Number(snapshot.updatedAt||0)>=Number(prior.updatedAt||0)){this.recoveredSnapshots.set(snapshot.trainId,snapshot);this.lastCheckpointAt.set(snapshot.trainId,Number(snapshot.updatedAt)||0);this.registerSnapshot(snapshot);if(source==='legacy')this.storageStats.legacyRestored+=1;else this.storageStats.recoveryRestored+=1;}}\n  async restoreRecoveryState(){const now=Date.now(),cutoff=now-RECOVERY_RETENTION_MS;try{for(const row of this.sql.exec('SELECT train_id,payload,updated_at FROM snapshots WHERE updated_at >= ?',cutoff)){let snapshot;try{snapshot=JSON.parse(row.payload);}catch{continue;}if(snapshot&&!snapshot.trainId)snapshot.trainId=text(row.train_id);this.rememberRecovered(snapshot,'legacy');}}catch{}try{const rows=await this.ctx.storage.list({prefix:RECOVERY_PREFIX});for(const[key,value]of rows){if(recoveryKeyExpired(key,now,RECOVERY_RETENTION_MS))continue;for(const snapshot of Array.isArray(value&&value.snapshots)?value.snapshots:[])this.rememberRecovered(snapshot);}}catch(error){this.storageStats.lastWriteError=`Recovery read: ${safeMessage(error)}`;}}\n"""
new="""  rememberRecovered(snapshot,source='recovery'){const compact=compactRecoverySnapshot(snapshot);if(!compact)return;const prior=this.recoveredSnapshots.get(compact.trainId);if(!prior||Number(compact.updatedAt||0)>=Number(prior.updatedAt||0)){this.recoveredSnapshots.set(compact.trainId,compact);this.lastCheckpointAt.set(compact.trainId,Number(compact.updatedAt)||0);this.registerSnapshot(compact);if(source==='legacy')this.storageStats.legacyRestored+=1;else this.storageStats.recoveryRestored+=1;}}\n  async restoreRecoveryState(){const now=Date.now(),cutoff=now-RECOVERY_RETENTION_MS;try{for(const row of this.sql.exec('SELECT train_id,payload,updated_at FROM snapshots WHERE updated_at >= ? ORDER BY updated_at DESC LIMIT ?',cutoff,MAX_RECOVERED_SNAPSHOTS)){let snapshot;try{snapshot=JSON.parse(row.payload);}catch{continue;}if(snapshot&&!snapshot.trainId)snapshot.trainId=text(row.train_id);this.rememberRecovered(snapshot,'legacy');}}catch{}try{let end='';for(let page=0;page<RECOVERY_LOAD_MAX_PAGES;page+=1){const options={prefix:RECOVERY_PREFIX,reverse:true,limit:RECOVERY_LOAD_PAGE_SIZE,noCache:true};if(end)options.end=end;const rows=await this.ctx.storage.list(options);if(!rows.size)break;let oldest='';for(const[key,value]of rows){oldest=key;if(recoveryKeyExpired(key,now,RECOVERY_RETENTION_MS))continue;for(const snapshot of Array.isArray(value&&value.snapshots)?value.snapshots:[])this.rememberRecovered(snapshot);}if(rows.size<RECOVERY_LOAD_PAGE_SIZE||!oldest)break;end=oldest;}}catch(error){this.storageStats.lastWriteError=`Recovery read: ${safeMessage(error)}`;}this.pruneMemory(now,true);}\n"""
worker=one(worker,old,new,'bounded recovery restore')
old_prune="  pruneMemory(now=Date.now()){if(now-this.lastMemoryPruneAt<60000)return;this.lastMemoryPruneAt=now;for(const[trainId,until]of this.hotTrainUntil)if(until<=now)this.hotTrainUntil.delete(trainId);for(const[trainId,snapshot]of this.liveSnapshots)if(now-Number(snapshot.updatedAt||0)>LIVE_RETENTION_MS)this.liveSnapshots.delete(trainId);for(const[trainId,snapshot]of this.recoveredSnapshots)if(now-Number(snapshot.updatedAt||0)>RECOVERY_RETENTION_MS){this.recoveredSnapshots.delete(trainId);this.lastCheckpointAt.delete(trainId);}}\n  async cleanupRecoveryStorage(now=Date.now()){if(now-this.lastStorageCleanupAt<6*60*60*1000)return;this.lastStorageCleanupAt=now;try{const rows=await this.ctx.storage.list({prefix:RECOVERY_PREFIX}),expired=[...rows.keys()].filter(key=>recoveryKeyExpired(key,now,RECOVERY_RETENTION_MS));for(let i=0;i<expired.length;i+=100)await this.ctx.storage.delete(expired.slice(i,i+100));}catch(error){this.storageStats.lastWriteError=`Recovery cleanup: ${safeMessage(error)}`;}}"
new_prune="""  trimSnapshotMap(map,retention,max,now){for(const[trainId,snapshot]of map)if(now-Number(snapshot.updatedAt||0)>retention)map.delete(trainId);if(map.size>max){const oldest=[...map.entries()].sort((a,b)=>Number(a[1]&&a[1].updatedAt||0)-Number(b[1]&&b[1].updatedAt||0));for(let i=0;i<oldest.length-max;i+=1)map.delete(oldest[i][0]);}}\n  rebuildMemoryIndexes(now=Date.now()){this.memoryServiceIndex=new Map();this.memoryHeadIndex=new Map();this.memoryOriginIndex=new Map();for(const[trainId,snapshot]of this.recoveredSnapshots)if(!this.liveSnapshots.has(trainId))this.registerSnapshot(snapshot);for(const snapshot of this.liveSnapshots.values())this.registerSnapshot(snapshot);this.lastIndexRebuildAt=now;}\n  pruneMemory(now=Date.now(),force=false){if(!force&&now-this.lastMemoryPruneAt<60000)return;this.lastMemoryPruneAt=now;for(const[trainId,until]of this.hotTrainUntil)if(until<=now)this.hotTrainUntil.delete(trainId);this.trimSnapshotMap(this.liveSnapshots,LIVE_RETENTION_MS,MAX_LIVE_SNAPSHOTS,now);this.trimSnapshotMap(this.recoveredSnapshots,RECOVERY_RETENTION_MS,MAX_RECOVERED_SNAPSHOTS,now);for(const trainId of [...this.lastCheckpointAt.keys()])if(!this.liveSnapshots.has(trainId)&&!this.recoveredSnapshots.has(trainId))this.lastCheckpointAt.delete(trainId);if(force||now-this.lastIndexRebuildAt>=INDEX_REBUILD_MS)this.rebuildMemoryIndexes(now);}\n  async cleanupRecoveryStorage(now=Date.now()){if(now-this.lastStorageCleanupAt<6*60*60*1000)return;this.lastStorageCleanupAt=now;try{for(let page=0;page<8;page+=1){const rows=await this.ctx.storage.list({prefix:RECOVERY_PREFIX,limit:100,noCache:true});if(!rows.size)break;const expired=[];let sawFresh=false;for(const key of rows.keys()){if(recoveryKeyExpired(key,now,RECOVERY_RETENTION_MS))expired.push(key);else{sawFresh=true;break;}}if(expired.length)await this.ctx.storage.delete(expired);if(sawFresh||expired.length<100)break;}}catch(error){this.storageStats.lastWriteError=`Recovery cleanup: ${safeMessage(error)}`;}}"""
worker=one(worker,old_prune,new_prune,'bounded memory and cleanup')
worker=one(worker,"for(const[trainId,snapshot]of applied.snapshots){this.liveSnapshots.set(trainId,snapshot);this.registerSnapshot(snapshot);const plan=shouldQueueRecovery({types:[...(typesByTrain.get(trainId)||[])],snapshot,hot:this.isHot(trainId,now),lastCheckpointAt:this.lastCheckpointAt.get(trainId)||0,now});if(plan.queue)this.queueRecovery(snapshot,plan.reason);}","for(const[trainId,snapshot]of applied.snapshots){const live=compactLiveSnapshot(snapshot,{historyLimit:this.isHot(trainId,now)?4:0});if(live){this.liveSnapshots.set(trainId,live);this.registerSnapshot(live);}const plan=shouldQueueRecovery({types:[...(typesByTrain.get(trainId)||[])],snapshot,hot:this.isHot(trainId,now),lastCheckpointAt:this.lastCheckpointAt.get(trainId)||0,now});if(plan.queue)this.queueRecovery(snapshot,plan.reason);}",'compact live persist')
write('kerbside-train-movement-worker/worker.js',worker)

for path in ['kerbside-train-movement-worker/worker.js','kerbside-train-movement-worker/movement-storage-policy.js','kerbside-train-movement-worker/movement-storage-policy.test.mjs']:
    subprocess.run(['node','--check',path],check=True)
subprocess.run(['node','--test','kerbside-train-movement-worker/movement-core.test.mjs'],check=True)
print('0.9.34 memory safety checks passed')
