from pathlib import Path
import json,re
root=Path('strikewatch-source')

def repl(path, old,new,count=1):
 p=root/path; t=p.read_text();
 if t.count(old)<count: raise SystemExit(f'missing {path}: {old[:80]}')
 p.write_text(t.replace(old,new,count),newline='\n')

repl(Path('js/00-core.js'),"const BUILD_VERSION = '12.164';","const BUILD_VERSION = '12.165';")
repl(Path('js/00-core.js'),"const BUILD_NAME = 'Lean Standalone';","const BUILD_NAME = 'CSS Ownership Baseline';")
repl(Path('js/00-core.js'),"const BUILD_ID = '12.164.0-lean-standalone';","const BUILD_ID = '12.165.0-css-ownership-baseline';")
idx=root/'index.html'; t=idx.read_text(); t=t.replace('Strikewatch 12.164: Lean Standalone','Strikewatch 12.165: CSS Ownership Baseline').replace('12.164.0-lean-standalone','12.165.0-css-ownership-baseline').replace('>12.164</b>','>12.165</b>');
link='<link rel="stylesheet" href="css/game.css?v=12.165.0-css-ownership-baseline" />'
t=t.replace(link,link+'\n<link rel="stylesheet" href="css/compact-navigation.css?v=12.165.0-css-ownership-baseline" />',1)
idx.write_text(t,newline='\n')
(root/'RELEASE.json').write_text(json.dumps({'version':'12.165','name':'CSS Ownership Baseline','build_id':'12.165.0-css-ownership-baseline'},indent=2)+'\n',newline='\n')

cssp=root/'css/game.css'; css=cssp.read_text(); marker='/* --- Build 12.163: compact navigator and alert alignment'
pos=css.find(marker)
if pos<0: raise SystemExit('12.163 CSS marker missing')
block=css[pos:].strip()+'\n'
if not block.endswith('}\n'): raise SystemExit('unexpected CSS tail')
cssp.write_text(css[:pos].rstrip()+'\n',newline='\n')
(root/'css/compact-navigation.css').write_text('''/* Compact club navigation and fixed management-alert ownership.\n   Extracted from game.css in Build 12.165 without changing cascade order. */\n\n'''+block,newline='\n')

bp=root/'build.py'; b=bp.read_text()
b=b.replace('BUNDLE_PATH = ROOT / "js" / "strikewatch.dev.js"\n','BUNDLE_PATH = ROOT / "js" / "strikewatch.dev.js"\nCSS_PATHS = (ROOT / "css" / "game.css", ROOT / "css" / "12.161-audit-fixes.css", ROOT / "css" / "compact-navigation.css")\n',1)
b=b.replace('''    css_path = ROOT / "css" / "game.css"\n    release_css_path = ROOT / "css" / "12.161-audit-fixes.css"\n    index_path = ROOT / "index.html"\n    if not css_path.exists() or not index_path.exists():\n        raise FileNotFoundError("index.html or css/game.css is missing")\n''','''    index_path = ROOT / "index.html"\n    if not all(path.exists() for path in CSS_PATHS) or not index_path.exists():\n        raise FileNotFoundError("index.html or an ordered CSS source is missing")\n''',1)
b=b.replace('''    css = css_path.read_text(encoding="utf-8").rstrip() + "\\n\\n" + release_css_path.read_text(encoding="utf-8").rstrip()\n''','''    css_sources = [path.read_text(encoding="utf-8").rstrip() for path in CSS_PATHS]\n    css = "\\n\\n".join(css_sources)\n''',1)
b=b.replace('''    html = re.sub(\n        r'<link rel="stylesheet" href="css/game\\.css\\?v=[^"]+"\\s*/>',\n        lambda _match: '<style>\\n' + release_css + '\\n</style>',\n        html,\n        count=1,\n    )\n''','''    html = re.sub(\n        r'<link rel="stylesheet" href="css/game\\.css\\?v=[^"]+"\\s*/>\\s*<link rel="stylesheet" href="css/compact-navigation\\.css\\?v=[^"]+"\\s*/>',\n        lambda _match: '<style>\\n' + release_css + '\\n</style>',\n        html,\n        count=1,\n    )\n''',1)
insert='''\n\ndef css_debt_report(version: str) -> dict:\n    texts = {path.name: path.read_text(encoding="utf-8") for path in CSS_PATHS}\n    combined = "\\n".join(texts.values())\n    report = {\n        "version": version,\n        "stylesheets": len(texts),\n        "total_lines": sum(value.count("\\n") for value in texts.values()),\n        "game_css_lines": texts["game.css"].count("\\n"),\n        "important_declarations": combined.count("!important"),\n        "media_queries": combined.count("@media"),\n        "owned_compact_navigation_lines": texts["compact-navigation.css"].count("\\n"),\n    }\n    budgets = {\n        "game_css_lines_max": 31700,\n        "important_declarations_max": 2182,\n        "media_queries_max": 474,\n    }\n    report["budgets"] = budgets\n    report["within_budget"] = (\n        report["game_css_lines"] <= budgets["game_css_lines_max"]\n        and report["important_declarations"] <= budgets["important_declarations_max"]\n        and report["media_queries"] <= budgets["media_queries_max"]\n    )\n    return report\n'''
b=b.replace('\ndef main() -> None:\n',insert+'\ndef main() -> None:\n',1)
b=b.replace('''    report_path.write_text(json.dumps(report, indent=2) + "\\n", encoding="utf-8", newline="\\n")\n    if report["javascript_raw_reduction_percent"] < 2.5:\n''','''    report_path.write_text(json.dumps(report, indent=2) + "\\n", encoding="utf-8", newline="\\n")\n    css_report = css_debt_report(version)\n    css_report_path = ROOT / "dist" / f"strikewatch-build-{version}-css-debt.json"\n    css_report_path.write_text(json.dumps(css_report, indent=2) + "\\n", encoding="utf-8", newline="\\n")\n    if not css_report["within_budget"]:\n        raise RuntimeError(f"CSS debt budget exceeded: {css_report}")\n    if report["javascript_raw_reduction_percent"] < 2.5:\n''',1)
b=b.replace('''    print(f"Release size report: {report_path}")\n''','''    print(f"Release size report: {report_path}")\n    print(f"CSS debt report: {css_report_path}")\n''',1)
bp.write_text(b,newline='\n')

h=root/'HANDOFF.md'; t=h.read_text(); t=t.replace('Build: **12.164 — Lean Standalone**','Build: **12.165 — CSS Ownership Baseline**',1).replace('Build ID: `12.164.0-lean-standalone`','Build ID: `12.165.0-css-ownership-baseline`',1).replace('strikewatch-build-12.164.html','strikewatch-build-12.165.html',1); pos=t.find('Build 12.164'); note='Build 12.165 begins the staged CSS-debt cleanup by moving the compact navigator and mobile management-alert rules out of the 31k-line monolith into `css/compact-navigation.css` while preserving their final cascade position. The build now emits and enforces a CSS-debt report. See `AUDIT-12.165.md`.\n\n'; t=t[:pos]+note+t[pos:]; h.write_text(t,newline='\n')
a=root/'AGENTS.md'; t=a.read_text(); anchor='## Current release note\n\n'; note='Build 12.165 owns the first CSS boundary: compact navigation and the phone management alert live in `css/compact-navigation.css`, loaded after the legacy and 12.161 layers. Do not move them back into `game.css`. Keep the CSS debt report within budget and preserve stylesheet order. See `AUDIT-12.165.md`.\n\n'; t=t.replace(anchor,anchor+note,1); a.write_text(t,newline='\n')
for n in ['README.md','PROJECT.md','00-READ-FIRST-GPT.md']:
 p=root/n; t=p.read_text().replace('12.164','12.165',1); p.write_text(t,newline='\n')
c=root/'CHANGELOG.md'; t=c.read_text(); entry='''## 12.165 — CSS Ownership Baseline\n\n- Extracts compact navigation and mobile alert rules from `game.css` into an owned stylesheet without changing cascade order.\n- Adds deterministic CSS debt reporting and non-growth budgets for monolith lines, `!important` declarations and media queries.\n- See `AUDIT-12.165.md`.\n\n'''; t=t.replace('# Strikewatch changelog\n','# Strikewatch changelog\n\n'+entry,1); c.write_text(t,newline='\n')
(root/'AUDIT-12.165.md').write_text('''# Build 12.165 — CSS Ownership Baseline\n\n## Audit item\n\nBegins the staged response to the CSS override-debt finding. A wholesale cascade rewrite is too risky, so this release creates the first explicit ownership boundary and prevents further silent growth.\n\n## Change\n\nThe Build 12.163 compact-navigation and mobile management-alert block is removed from the tail of `css/game.css` and placed in `css/compact-navigation.css`. The development page loads it after `game.css`; the standalone build concatenates it after the existing 12.161 audit layer, preserving its effective final cascade position. Declarations are unchanged.\n\n## Debt guardrails\n\n`dist/strikewatch-build-12.165-css-debt.json` records total CSS lines, monolith lines, `!important` count, media-query count and owned compact-layer lines. The build fails when the established non-growth budgets are exceeded.\n\n## Verification\n\n- Two builds produce identical bundle, standalone, size report and CSS debt report hashes.\n- Source, generated and standalone JavaScript parse.\n- Ordered CSS concatenation contains the compact layer exactly once and after the legacy layers.\n- Root `cod.html` is byte-identical to the standalone.\n- No selectors or declarations in the extracted block changed.\n''',newline='\n')